#!/usr/bin/env bash

# =========================
# ZINOVA LS COLORS
# =========================

export LS_COLORS="\
di=1;94:\
ln=1;96:\
ex=1;92:\
*.rs=1;95:\
*.py=1;93:\
*.sh=1;92:\
*.md=1;37:\
*.json=1;36:\
*.toml=1;33:\
*.yaml=1;33:\
*.yml=1;33:\
*.zip=1;91:\
*.tar=1;91"
