#!/usr/bin/env bash

# =========================
# Workspace Root
# =========================

export ZINOVA_WORKSPACES="$HOME/WORKSPACES"



# =========================
# ZINOVA
# =========================

export ZINOVA_ROOT="$ZINOVA_WORKSPACES/ZINOVA"

export ZINOVA_CORE="$ZINOVA_ROOT/ZINOVA-CORE"

export ZINOVA_PLATFORM="$ZINOVA_ROOT/zinova-platform"

export ZINOVA_CORE_SANDBOX="$ZINOVA_ROOT/ZINOVA-CORE-SANDBOX"

export ZINOVA_PLATFORM_SANDBOX="$ZINOVA_ROOT/ZINOVA-PLATFORM-SANDBOX"

export ZINOVA_SHELL_HOME="$HOME/WORKSPACES/SHARED/zinova-shell"

# =========================
# ZEIS / SHARED
# =========================

export ZINOVA_SHARED="$ZINOVA_WORKSPACES/SHARED"

export ZINOVA_ZEIS="$ZINOVA_SHARED/ZEIS"



# =========================
# ARZIN
# =========================

export ARZIN_ROOT="$ZINOVA_WORKSPACES/ARZIN"

export ARZIN_CORE="$ARZIN_ROOT/ARZIN-CORE"

export ARZIN_SANDBOX="$ARZIN_ROOT/ARZIN-CORE-SANDBOX"
